# Development override file
# This file is automatically used by docker-compose for development
version: '3.8'

services:
  backend:
    volumes:
      # Mount source code for hot reloading in development
      - ./backend:/app
      - /app/__pycache__
      - /app/venv
    environment:
      - DEBUG=true
      - ENVIRONMENT=development
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    # For development, you might want to run React dev server instead
    # Uncomment the following to use React dev server
    # build:
    #   target: build
    # command: ["npm", "start"]
    # ports:
    #   - "3000:3000"
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules
    environment:
      - NODE_ENV=development