# Production docker-compose configuration
# Use with: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
version: '3.8'

services:
  db:
    restart: always
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  backend:
    restart: always
    environment:
      - DEBUG=false
      - ENVIRONMENT=production
    # Remove volume mounts for production

  frontend:
    restart: always
    environment:
      - NODE_ENV=production

volumes:
  postgres_prod_data:
    driver: local